name: Run clang-tidy

on: [pull_request]
jobs:
  clang-tidy:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6

      - name: Update
        run: |
          sudo apt-get update -y -qq

      - name: Install clang-tidy
        run: |
          sudo apt install clang-tidy

      - name: Print system info
        run: |
          echo '::group::CPU / OS info'
          lscpu
          uname -a
          echo '::endgroup::'
          echo '::group::Package versions'
          gcc --version
          which gcc
          clang-tidy --version
          which clang-tidy
          echo '::endgroup::'

      - name: Compile problems
        run: |
          cd eos
          make USE_CLANG_TIDY=TRUE PRECISION=LONG_DOUBLE

