name: Test compilation

on: [pull_request]
jobs:
  compilation:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7

      - name: update
        run: |
          sudo apt-get update -y -qq

      - name: report GCC version
        run: gcc --version

      - name: Compile problems with __float128
        run: |
          cd tests
          make PRECISION=FLOAT128

      - name: Compile problems with long double
        run: |
          cd tests
          make clean
          make PRECISION=LONG_DOUBLE

      - name: Compile problems with double
        run: |
          cd tests
          make clean
          make PRECISION=DOUBLE

