name: Run tests

on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: update
        run: |
          sudo apt-get update -y -qq

      - name: install conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: install GCC 15
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda create -y -n gcc15 -c conda-forge gcc=15.1.0 gxx=15.1.0

      - name: Set environment variables
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda activate gcc15
          echo "CC=$(which gcc)" >> $GITHUB_ENV
          echo "CXX=$(which g++)" >> $GITHUB_ENV
          echo "$(dirname $(which gcc))" >> $GITHUB_PATH

      - name: report GCC version
        run: gcc --version

      - name: Compile tests
        run: |
          cd tests
          make -j 4

      - name: Run test_n_derivs
        run: |
          cd tests
          ./test_n_derivs > test.out
          diff test.out ci-benchmarks/test_n_derivs.out

      - name: Run test_fermi
        run: |
          cd tests
          ./test_fermi > test2.out
          diff test2.out ci-benchmarks/test_fermi.out
