name: Run test Fermi

on: [pull_request]
jobs:
  test_fermi:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6

      - name: update
        run: |
          sudo apt-get update -y -qq

      - name: report GCC version
        run: gcc --version

      - name: Compile tests
        run: |
          cd tests
          make -j 4 test_fermi

      - name: Run test_fermi
        run: |
          cd tests
          ./test_fermi > test2.out
          diff test2.out ci-benchmarks/test_fermi.out
