name: Plot generation

on: [pull_request]
jobs:
  plot-generator:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6

      - name: update
        run: |
          sudo apt-get update -y -qq

      - name: Print system info
        run: |
          echo '::group::CPU info'
          lscpu
          echo '::endgroup::'
          echo '::group::GCC version'
          gcc --version
          echo '::endgroup::'

      - name: Compile plot generator
        run: |
          cd plots
          make clean
          make PRECISION=DOUBLE FULL_OPTIMIZE=FALSE

      - name: check results
        run: |
          cd plots
          ./generate_maxwell_data
          diff maxwell_p64_npts200.txt ci-benchmarks/maxwell_p64_npts200.txt
