name: Run test_n_derivs

on: [pull_request]
jobs:
  test_n_derivs:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7

      - name: update
        run: |
          sudo apt-get update -y -qq

      - name: report GCC version
        run: gcc --version

      - name: Compile tests
        run: |
          cd tests
          make -j 4 test_n_derivs

      - name: Run test_n_derivs
        run: |
          cd tests
          ./test_n_derivs > test.out
          diff test.out ci-benchmarks/test_n_derivs.out
