name: Run Maxwell tests

on: [pull_request]
jobs:
  test_maxwell:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6

      - name: update
        run: |
          sudo apt-get update -y -qq

      - name: report GCC version
        run: gcc --version

      - name: Compile test
        run: |
          cd tests
          make -j 4 test_maxwell

      - name: Run test_maxwell
        run: |
          cd tests
          ./test_maxwell > test3.out
          diff test3.out ci-benchmarks/test_maxwell.out
